name: Run Tests
# This workflow runs the tests on the app outside of it's docker container
# This is for operational efficiency. proper end-to-end tests should be handled elsewhere

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, edited]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  changes:
    name: "Detect Changes"
    runs-on: ubuntu-slim
    outputs:
      migrations: ${{ steps.filter.outputs.migrations }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            migrations:
              - 'apps/**/migrations/*'
  # TODO: Include a step that prevents migration code from being in the same commit as non-migration code.
  tests:
    name: "Integration Tests w/ Docker"
    runs-on: ubuntu-22.04
    # services:
    # # Make sure all services have their environment variables match what is expected as defined in `.env.testing`
    #   postgres:
    #     image: postgres:18
    #     env:
    #       POSTGRES_DB: hairbrush_db_test
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: test_password
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    #     ports:
    #       - 5432:5432
    # steps:
    #   - uses: actions/checkout@v4

    #   - name: Install uv
    #     uses: astral-sh/setup-uv@v3
    #     with:
    #       version: "0.9.17"
    #       enable-cache: true

    #   - name: Set up Python ${{ matrix.python-version }}
    #     uses: actions/setup-python@v5
    #     with:
    #       python-version: ${{ matrix.python-version }}
    #   - name: Install Dependencies
    #     run: |
    #       uv sync

    #   - name: Set Testing Env Vars
    #     uses: cardinalby/export-env-action@v2
    #     with:
    #       envFile: '.env.testing'

    #   - name: Run Tests
    #     # env set by previous action
    #     run: |
    #       uv run manage.py test
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v4
        with:
          just-version: '1.50.0'
      - name: Run CI Tests
        run: |
          just ci test
