name: Run Tests & Maybe Build
# This workflow runs the tests on the app outside of it's docker container
# This is for operational efficiency. proper end-to-end tests should be handled elsewhere

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "my_journey/**"
  pull_request:
    types: [opened, synchronize, edited]
    paths-ignore:
      - "my_journey/**"
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  changes:
    name: "Detect Changes"
    runs-on: ubuntu-slim
    outputs:
      migrations: ${{ steps.filter.outputs.migrations }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            migrations:
              - 'apps/**/migrations/*'
  # TODO: Include a step that prevents migration code from being in the same commit as non-migration code.
  tests:
    name: "Integration Tests w/ Docker"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v4
        with:
          just-version: '1.50.0'
      - name: Run CI Tests
        run: |
          just ci test

  build:
    name: Build Docker Image
    runs-on: ubuntu-22.04
    concurrency:
      group: build-deploy
      cancel-in-progress: true
    needs: [changes, tests]
    if: (needs.changes.outputs.migrations == 'false' || github.event_name == 'workflow_dispatch') && (github.event_name != 'pull_request')
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    outputs:
      digest: ${{ steps.push.outputs.digest }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ghcr.io/eligrubbs/django-app-experiment
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
      - uses: docker/build-push-action@v7
        id: push
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: .
          provenance: false # disable many artifacts for one workflow run to show up in the UI.
          platforms: linux/amd64
      - name: Export digest
        run: echo "${{ steps.push.outputs.digest }}" > digest.txt
      - uses: actions/upload-artifact@v7
        with:
          name: image-digest
          path: digest.txt
          archive: false
